project:
  type: website

execute:
  freeze: auto

website:
  title: "Experiments with price stats"
  repo-url: https://sergegoussev.github.io/price_stats_experiments/docs/
  repo-actions: [source]
  bread-crumbs: true
  page-navigation: true
  back-to-top-navigation: true
  search: true
  sidebar:
    style: "docked"
    type: "dark"
    search: true
    logo: docs/images/logo_bauhaus.jpeg
    border: true
    tools:
      - icon: github
        menu:
        - text: Source
          href: https://github.com/sergegoussev/price_stats_experiments
        - text: Report a bug
          href: https://github.com/sergegoussev/price_stats_experiments/issues
    contents:
      - href: docs/index.qmd
        text: Overview
      - section:
        text: Notes by method
        contents:
        - href: docs/notes_on_bilateral_index_methods.qmd
        - href: docs/sampling_methods.qmd
      - href: docs/empirical_experiments.qmd



format:
  html:
    theme: 
      dark: darkly
      light: cosmo
    css: docs/styles.css
    toc: true



