project:
  type: website

execute:
  freeze: auto

website:
  title: "Experiments with price stats"
  repo-url: https://github.com/sergegoussev/price_stats_experiments
  issue-url: https://github.com/sergegoussev/price_stats_experiments/issues/new
  repo-actions: [source, issue]
  bread-crumbs: true
  page-navigation: true
  back-to-top-navigation: true
  search: true
  sidebar:
    style: "docked"
    type: "dark"
    search: true
    logo: docs/images/logo_bauhaus.jpeg
    logo-href: https://sergegoussev.github.io/price_stats_experiments/docs/
    title: "Experiments with price stats"
    border: true
    tools:
      - icon: github
        menu:
        - text: Source
          href: https://github.com/sergegoussev/price_stats_experiments
        - text: Report a bug
          href: https://github.com/sergegoussev/price_stats_experiments/issues
    contents:
      - href: docs/index.qmd
        text: Overview
      - section:
        text: Notes by method
        contents:
        - href: docs/notes_on_methods/bilateral_indices.qmd
        - href: docs/notes_on_methods/sampling_with_scanner.qmd
      - href: docs/empirical_experiments/experiments_catalogue.qmd



format:
  html:
    theme: 
      dark: cyborg
      light: flatly
    css: docs/styles.css
    toc: true



