project:
  type: website

execute:
  freeze: auto

website:
  title: "Experiments with price statistics"
  repo-actions: [source]
  bread-crumbs: true
  page-navigation: true
  back-to-top-navigation: true
  search: true
  sidebar:
    style: "docked"
    type: "dark"
    search: true
    border: true
    tools:
      - icon: github
        href: https://sergegoussev.github.io/price_index_experiments/
        text: GitHub account for this site
    contents:
      - href: docs/index.qmd
        text: Overview
      - href: docs/price_index_experiments.qmd


format:
  html:
    theme: 
      dark: darkly
      light: cosmo
    css: docs/styles.css
    toc: true



