---
title: "Notes on bilateral price index methods"
author: Serge Goussev
date: 2024-09-27
format:
  html:
    toc: true
    toc-expand: 2
    html-math-method:
      method: mathjax
      url: "https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"
    other-links:
      - text: Aizcorbe (2014) A Practical Guide to Price Index and Hedonic Techniques
        href: https://global.oup.com/academic/product/a-practical-guide-to-price-index-and-hedonic-techniques-9780198702429?cc=ca&lang=en&      
      - text: Balk (2008) Price and Quantity Index Numbers
        href: https://www.cambridge.org/core/books/price-and-quantity-index-numbers/9A54AF90399685AED460F52821BD6225
      - text: "CPI Manual: Concepts and Methods (2020)"
        href: https://www.imf.org/-/media/Files/Data/CPI/cpi-manual-concepts-and-methods.ashx
      - text: "UN Task Team e-handbook: Bilateral Price Index Methods"      
        href: https://unstats.un.org/wiki/display/GWGSD/Bilateral+price+index+methods
---

# Overview

This page provides an overview of Bilateral Price Index methods. Several sources are used (included in the links to the page) to go over key concepts. Emprical examples are linked from this page or can be found in the main guide

## The concept of price index methods

> A price index provides an aggregate measure of price change for a particular product segment, industry, or overall economy. ... \[They compare\] the cost of purchasing a set of goods at different points in time. This "set of goods" is often referred to as the "market basket" or the "bundle" of goods. - Aizcorbe (2014)

# Main formulas

## Laspeyres index

The simplest formula (and one that is commonly used) is the Laspeyres index:

$I^{L}_{0,1} = \frac{\sum_{m=1}^{M}(P_{m,1}Q_{m,0})}{\sum_{m=1}^{M}(P_{m,0}Q_{m,0}})$

Where P's and Q's denote prices and quantities, and 0 and 1 denote two points in time.

If M goods are sold in both periods (note that an overlap is needed), we can compare the the cost of purchasing the same goods we bought in period 1 with a certain period in the future.

We can also write the Laspeyres as the weighted arithmetic average of the price change of the individual products in the index

$I^L_{0,1} = \sum_{m=1}^{M} (w_{m,0}\frac{P_{m,1}}{P_{m,0}})$ such that $w_{m,0} = (P_{m,0}Q_{m,0})/\sum_{m=1}^{M}(P_{m,0}Q_{m,0})$

give the ratio of good m's expenditure to total expenditure, or could also be considered the relative importance or share of the product. There are some key nuances with this approach:

-   Products sold in both periods are included in both periods, thus new products are omitted.
-   We fix the relative importance of the goods for both periods based on period 1 weight, thus we do not reflect changes in composition over time (substitution). This can be convenient as we need weights only for the base period.
    -   Most price indices are variants of the Laspeyres, such as the Lowe (which compare the prices from the current month with the previous month, but use weights from a year before that)

## Paashe Index

Similar to the Lasperyes, however uses a different basket (the one from the pricing period:

$I^P_{0,1} = \sum_{m=1}^M (P_{m,1}Q_{m,1}) / \sum_{m=1}^M
 (P_{m,0}Q_{m,1})$ The Paasche may also be expressed as a function of the weighted average (i.e. shares):

$I^P_{0,1} = 1/ \sum_{m=1}^M (w_{m,1} \frac{P_{m,0}}{P_{m,1}})$ such that $w_{m,1} = (P_{m,1}Q_{m,1})/ \sum_{m=1}^M (w_{m,1}P_{m,0}Q_{m,1})$

The Laspeyres and Paasche include prices and quantities in both periods, and both use the same relatives with different expenditure shares.

## Fisher Index

The Fisher does a geometric average of the Laspeyres and the Paasche:

$I^F_{0,1} = (I^L_{0,1}I^P_{0,1})^\frac{1}{2}$

The Fisher thus uses expenditure from both periods and thus provides relative importance that are more closely aligned with the goods actually sold. As the Fisher satisfies homogeneity, symmetry, and the time reversal test (the price change from the base to the current should be the inverse of the current to the base) - thus it doesn't matter what period is chosen as the base.

## Törnqvist Index

Similar to the Fisher, however it takes the average of the weights instead of averaging the two indices

In logged form:

$lnI^T_{0,1}=\sum^M_{m=1}(w_{m,0}+w_{m,1})/2(ln\frac{P_{m,1}}{P_{m,0}})$

## Jevons Index

The Jevons is unweighted geometric mean. Similar to the Törnqvist, in logged form:

$lnI^J_{0,1} = \frac{1}{M} \sum^M_{m=1}ln(P_{m,1}/P_{m,0})$

The Jevons takes the unweighted average by replacing the $(w_{m,0}+w_{m,1})/2$ with $1/M$, thus giving each model equal weight

# Empirical examples

-   See an application of these methods locally using [various data examples](https://sergegoussev.github.io/price_stats_experiments/docs/price_index_experiments.html#category=bilateral%20index%20methods)