on:
  workflow_dispatch:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
      
name: Quarto Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    defaults:
      run:
        # Use a login shell to activate the Conda environment
        shell: bash -l {0}
        
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Setup Micromamba
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: environment.yml
          environment-name: price_stats_experiments
          cache-environment: true

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      # Optional: Add a verification step to confirm the environment is active
      - name: Verify Conda environment is active
        run: |
          which python
          conda info --envs
          conda list

      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
